services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
    volumes:
      - './etc/pihole:/etc/pihole'
      - './etc/dnsmasq.d:/etc/dnsmasq.d'
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped