services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/etc/grafana/provisioning/datasources
      - ./grafana-data:/var/lib/grafana
    restart: unless-stopped