services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/main/docker/portainer/data:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped